language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Gbx8jbRXgkzps0e370lbVbSa0OGFy1nLPerYh+2AWmf4ahsh6q00RIyKEX6WM00Fum46uZGOQ8vYcEBEoQkYvUXWuk+ATG1W8a2ylSE0oGALHnYANv8SLAb+jar5NOvpOeQ8qhYXkeiLrHHsHRV28ppEDwnJZhrF2fi70nwDbNVTMP9oPJTvDSG2xo9joS3HtR8pl6M+zd+6ivdEUndE/uWc8KKdORZDFiH2Gk7PxHYWKMlP9rC+ImsGFRmtZiYtFDUbqiPfYvUBN0VaMWmZ5F0hd4XayijwjwNHN+54waWShZSyQ84RAfUg/bZO52tOzYGgEyAI7o6J2Y9JVYbfPGuKuFWlPZEjr0YABHeXRIjot2lI8gptVzG5KMHnGzDbymVgABS85rCblf96c9yHpoqL9Wiftua+irr90gJdJ140Dd4p2rVJzmuZ0FQJIehrKXaK+XDFsaxksI6hb65Lca+VZdHzIdZ8LXo0PHZRfRvPnJNe7C8jX8MplTnee0pJV6g23wlJBsCONuD3Ub3iNGgJt7Z84kLyfxL5nFKslBf2cyhA1Z2kjLiWmlQnT202h0xcNdbIsh9nNW2zUbcqD1HM/lyYNwmu2dVcNNJdK7LR+hq5hFlI7IbNNa/TWF0AgXUBMy0tIWFAHbcFWeZrcmOOnQ0cMHfoNVW2o8Y6o28="
env:
  secure: "yA4tcNxT6dHf73pQOw4zkyFX7kJUCI6iZW2wgcK/IZPdyYjxz532PjHR172RhmkvUFCOuXEasv62RJ12lqIBZMZfhe0X4xnJEPcVzmrF0YjNcidhfy6vYIDut4D8Q7YTEp0/v0VVkm4N5f/M27J1F8qQmZjhDudF85OMuKzEigwCdcLpMnYFMX1EWm2kd2g+pvUQ2h/3ZpbQQEksLZG4Fr6Op5pE/Bg04vdfFJPYYurIGDEmPPxyoXJgQDVOzYbTVfcTjmciMcIK3S0xKo489d77QzPcbf3HWikAYJMgxtrAjpLhgZ2omVBQExmmqesjo6bvJSEn94AHWIkpxCkNmLK/Wmv8lmQ9W4g8h4PVL6A0LVJtjAvT7J0T4232haohWVaTTP8BV0KUpm7yhfYNjn76If3taVQkRRLi0/EOf3kthWohbFomtl0NANfJlFc5jgJz1qPPS5larnMzvHd2Wz1foS9GJgxaLuBNVhljU6WuzXolbpYO7owak/Aq1h3UOLc6Y5DUiHhZ10prD819UFu9o4DgDTDhkb1EPqtGUMkXOMQBbc6dxSF9xfKbTEEAegqA0BrZFUnMnaOBa19k9UTZElfHdW0nm3AfwRPGLciQ9Idg2gZ1bf3ZC01UEU0zpdCLYFhMas7yeH/eurl0DsKt+nMH469XFmPTG8UwEV4="
